import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.image.BufferedImage;
import java.io.BufferedReader;
import java.io.DataInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.StringTokenizer;
import javafx.stage.FileChooser;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.plaf.basic.BasicTabbedPaneUI;
import javax.swing.plaf.metal.MetalLookAndFeel;
import javax.swing.plaf.nimbus.NimbusLookAndFeel;
import javax.swing.plaf.synth.SynthLookAndFeel;
import javax.swing.text.View;
import joxy.JoxyLookAndFeel;
import org.netbeans.lib.awtextra.AbsoluteLayout;

public class Home extends javax.swing.JFrame {
    private final LocalLibrary localLibrary = new LocalLibrary();
    int a = 1;
    private JFileChooser fc = new JFileChooser();   
    boolean musicOn;
    public Home() {
        initComponents();
        this.setLocationRelativeTo(null);
        pnlProject.setVisible(false);
        //editPanel.setVisible(false);
        mediaPanel.setVisible(false);
        //tampilkanImage();
        pbtnPreviewProject.setVisible(false);
        pnlProjectInfo.setVisible(false);
        leftPageNumber.setVisible(false);
        rightPageNumber.setVisible(false);
        leftPagePanel.setVisible(false);
        rightPagePanel.setVisible(false);              
        
        localLibrary.getCanvas().addMouseListener(new MouseListener(){       
            @Override
            public void mouseClicked(MouseEvent e) {
                rightPage.setVisible(true); 
                localLibrary.dispose();
                
                pnlProject.setVisible(false);
                pnlProjectInfo.setVisible(false);
                leftPagePanel.setVisible(true);
                rightPagePanel.setVisible(true);
                leftPageNumber.setVisible(true);
                rightPageNumber.setVisible(true);
                
                editPanel.setVisible(false);
                mediaPanel.setVisible(false);
                rightPageNumber.setText("Cover");
                muzic m = new muzic();
                m.play();
                musicOn = true;
            }
            
            @Override
            public void mousePressed(MouseEvent e) {
                
            }

            @Override
            public void mouseReleased(MouseEvent e) {
                
            }

            @Override
            public void mouseEntered(MouseEvent e) {
                localLibrary.lbl8.setBackground(Color.LIGHT_GRAY);
            }

            @Override
            public void mouseExited(MouseEvent e) {
                localLibrary.lbl8.setBackground(Color.WHITE);
            }
        });        
    }
    
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlUtama = new javax.swing.JPanel();
        pnlProject = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        leftPagePanel = new javax.swing.JPanel();
        leftPage = new javax.swing.JLabel();
        editPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        rightPagePanel = new javax.swing.JPanel();
        rightPage = new javax.swing.JLabel();
        rightPageNumber = new javax.swing.JLabel();
        leftPageNumber = new javax.swing.JLabel();
        pnlProjectInfo = new javax.swing.JPanel();
        lblProject = new javax.swing.JLabel();
        lblCloseProject = new javax.swing.JLabel();
        mediaPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        contTextBox = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        lblText = new javax.swing.JLabel();
        contImage = new javax.swing.JPanel();
        btn1 = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();
        contAnimated = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        lblAnimated = new javax.swing.JLabel();
        contVideo = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        lblVideo = new javax.swing.JLabel();
        contSound = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        lblSound = new javax.swing.JLabel();
        contTemplate = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        lblTemplate = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        pbtnPreviewProject = new javax.swing.JPanel();
        lblProject6 = new javax.swing.JLabel();
        lblCloseProject6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jMenuItem26 = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem31 = new javax.swing.JMenuItem();
        jMenuItem32 = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem33 = new javax.swing.JMenuItem();
        jMenuItem34 = new javax.swing.JMenuItem();
        jMenuItem35 = new javax.swing.JMenuItem();
        jMenuItem36 = new javax.swing.JMenuItem();
        jMenuItem37 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        showEditPanel = new javax.swing.JCheckBoxMenuItem();
        showMediaPanel = new javax.swing.JCheckBoxMenuItem();
        jSeparator11 = new javax.swing.JPopupMenu.Separator();
        jMenuItem30 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem38 = new javax.swing.JMenuItem();
        jSeparator12 = new javax.swing.JPopupMenu.Separator();
        jCheckBoxMenuItem4 = new javax.swing.JCheckBoxMenuItem();
        jSeparator13 = new javax.swing.JPopupMenu.Separator();
        jMenuItem39 = new javax.swing.JMenuItem();
        jMenuItem40 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem41 = new javax.swing.JMenuItem();
        jMenuItem42 = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem43 = new javax.swing.JMenuItem();
        jMenuItem44 = new javax.swing.JMenuItem();
        jMenuItem45 = new javax.swing.JMenuItem();
        jMenuItem46 = new javax.swing.JMenuItem();
        jMenuItem47 = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        jMenuItem48 = new javax.swing.JMenuItem();
        jMenuItem49 = new javax.swing.JMenuItem();
        jMenu13 = new javax.swing.JMenu();
        jMenuItem50 = new javax.swing.JMenuItem();
        jMenuItem51 = new javax.swing.JMenuItem();
        jMenuItem52 = new javax.swing.JMenuItem();
        jMenuItem53 = new javax.swing.JMenuItem();
        jMenuItem54 = new javax.swing.JMenuItem();
        jMenuItem55 = new javax.swing.JMenuItem();
        jMenu14 = new javax.swing.JMenu();
        jMenuItem56 = new javax.swing.JMenuItem();
        jMenuItem57 = new javax.swing.JMenuItem();
        jMenuItem58 = new javax.swing.JMenuItem();
        jMenuItem59 = new javax.swing.JMenuItem();
        jMenuItem60 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem64 = new javax.swing.JMenuItem();
        jMenuItem65 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenuItem27 = new javax.swing.JMenuItem();
        jSeparator14 = new javax.swing.JPopupMenu.Separator();
        jMenuItem28 = new javax.swing.JMenuItem();
        jMenuItem29 = new javax.swing.JMenuItem();
        jMenuItem61 = new javax.swing.JMenuItem();
        jMenuItem62 = new javax.swing.JMenuItem();
        jSeparator15 = new javax.swing.JPopupMenu.Separator();
        jMenuItem63 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");
        setPreferredSize(new java.awt.Dimension(1220, 680));

        pnlUtama.setBackground(new java.awt.Color(74, 146, 172));

        pnlProject.setBackground(new java.awt.Color(244, 138, 0));

        jPanel7.setBackground(new java.awt.Color(204, 204, 255));

        leftPagePanel.setBackground(new java.awt.Color(102, 102, 102));
        leftPagePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        leftPage.setBackground(new java.awt.Color(255, 255, 255));
        leftPage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        leftPage.setOpaque(true);

        javax.swing.GroupLayout leftPagePanelLayout = new javax.swing.GroupLayout(leftPagePanel);
        leftPagePanel.setLayout(leftPagePanelLayout);
        leftPagePanelLayout.setHorizontalGroup(
            leftPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(leftPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        leftPagePanelLayout.setVerticalGroup(
            leftPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leftPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        editPanel.setBackground(new java.awt.Color(255, 200, 105));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Untitled-17.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.setOpaque(true);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Untitled-13.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.setOpaque(true);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Untitled-11.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.setOpaque(true);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Untitled-16.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.setOpaque(true);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Untitled-14.png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.setOpaque(true);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Untitled-12.png"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.setOpaque(true);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Untitled-15.png"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.setOpaque(true);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Untitled-18.png"))); // NOI18N
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.setOpaque(true);

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Untitled-19.png"))); // NOI18N
        jLabel22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel22.setOpaque(true);

        javax.swing.GroupLayout editPanelLayout = new javax.swing.GroupLayout(editPanel);
        editPanel.setLayout(editPanelLayout);
        editPanelLayout.setHorizontalGroup(
            editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );
        editPanelLayout.setVerticalGroup(
            editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        rightPagePanel.setBackground(new java.awt.Color(102, 102, 102));
        rightPagePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        rightPage.setBackground(new java.awt.Color(255, 255, 255));
        rightPage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rightPage.setOpaque(true);

        javax.swing.GroupLayout rightPagePanelLayout = new javax.swing.GroupLayout(rightPagePanel);
        rightPagePanel.setLayout(rightPagePanelLayout);
        rightPagePanelLayout.setHorizontalGroup(
            rightPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightPagePanelLayout.createSequentialGroup()
                .addComponent(rightPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        rightPagePanelLayout.setVerticalGroup(
            rightPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rightPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        rightPageNumber.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rightPageNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        leftPageNumber.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        leftPageNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(editPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(leftPagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rightPagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(21, 21, 21))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(leftPageNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rightPageNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(144, 144, 144))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(leftPagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rightPagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rightPageNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(leftPageNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
            .addComponent(editPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlProjectLayout = new javax.swing.GroupLayout(pnlProject);
        pnlProject.setLayout(pnlProjectLayout);
        pnlProjectLayout.setHorizontalGroup(
            pnlProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProjectLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlProjectLayout.setVerticalGroup(
            pnlProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProjectLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlProjectInfo.setBackground(new java.awt.Color(244, 138, 0));

        lblProject.setBackground(new java.awt.Color(255, 255, 255));
        lblProject.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        lblProject.setForeground(new java.awt.Color(240, 240, 240));
        lblProject.setAlignmentX(0.5F);
        lblProject.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblProject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblProjectMouseClicked(evt);
            }
        });

        lblCloseProject.setBackground(new java.awt.Color(229, 235, 240));
        lblCloseProject.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        lblCloseProject.setForeground(new java.awt.Color(255, 255, 255));
        lblCloseProject.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCloseProject.setText("x");
        lblCloseProject.setAlignmentX(0.5F);
        lblCloseProject.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCloseProject.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblCloseProject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseProjectMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlProjectInfoLayout = new javax.swing.GroupLayout(pnlProjectInfo);
        pnlProjectInfo.setLayout(pnlProjectInfoLayout);
        pnlProjectInfoLayout.setHorizontalGroup(
            pnlProjectInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProjectInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblProject, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCloseProject, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlProjectInfoLayout.setVerticalGroup(
            pnlProjectInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProjectInfoLayout.createSequentialGroup()
                .addComponent(lblCloseProject, javax.swing.GroupLayout.PREFERRED_SIZE, 24, Short.MAX_VALUE)
                .addGap(5, 5, 5))
            .addComponent(lblProject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        mediaPanel.setBackground(new java.awt.Color(244, 138, 0));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Content Explorer");

        jLabel10.setFont(new java.awt.Font("Broadway", 1, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText(">");

        contTextBox.setBackground(new java.awt.Color(244, 138, 0));
        contTextBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        contTextBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                contTextBoxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                contTextBoxMouseExited(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Broadway", 1, 48)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText(">");

        lblText.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        lblText.setForeground(new java.awt.Color(255, 255, 255));
        lblText.setText("Text Box");
        lblText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblTextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblTextMouseExited(evt);
            }
        });

        javax.swing.GroupLayout contTextBoxLayout = new javax.swing.GroupLayout(contTextBox);
        contTextBox.setLayout(contTextBoxLayout);
        contTextBoxLayout.setHorizontalGroup(
            contTextBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contTextBoxLayout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblText, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        contTextBoxLayout.setVerticalGroup(
            contTextBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(lblText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        contImage.setBackground(new java.awt.Color(244, 138, 0));
        contImage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        contImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                contImageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                contImageMouseExited(evt);
            }
        });

        btn1.setFont(new java.awt.Font("Broadway", 1, 48)); // NOI18N
        btn1.setForeground(new java.awt.Color(255, 255, 255));
        btn1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn1.setText(">");

        lblImage.setBackground(new java.awt.Color(255, 255, 255));
        lblImage.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        lblImage.setForeground(new java.awt.Color(255, 255, 255));
        lblImage.setText("Image & Photo");
        lblImage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImageMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblImageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblImageMouseExited(evt);
            }
        });

        javax.swing.GroupLayout contImageLayout = new javax.swing.GroupLayout(contImage);
        contImage.setLayout(contImageLayout);
        contImageLayout.setHorizontalGroup(
            contImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contImageLayout.createSequentialGroup()
                .addComponent(btn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        contImageLayout.setVerticalGroup(
            contImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        contAnimated.setBackground(new java.awt.Color(244, 138, 0));
        contAnimated.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                contAnimatedMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                contAnimatedMouseExited(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Broadway", 1, 48)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText(">");

        lblAnimated.setBackground(new java.awt.Color(255, 255, 255));
        lblAnimated.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        lblAnimated.setForeground(new java.awt.Color(255, 255, 255));
        lblAnimated.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAnimated.setText("Animated Graphics");
        lblAnimated.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAnimated.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAnimatedMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAnimatedMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAnimatedMouseExited(evt);
            }
        });

        javax.swing.GroupLayout contAnimatedLayout = new javax.swing.GroupLayout(contAnimated);
        contAnimated.setLayout(contAnimatedLayout);
        contAnimatedLayout.setHorizontalGroup(
            contAnimatedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contAnimatedLayout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAnimated, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        contAnimatedLayout.setVerticalGroup(
            contAnimatedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contAnimatedLayout.createSequentialGroup()
                .addComponent(lblAnimated, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        contVideo.setBackground(new java.awt.Color(244, 138, 0));
        contVideo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                contVideoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                contVideoMouseExited(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Broadway", 1, 48)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText(">");

        lblVideo.setBackground(new java.awt.Color(255, 255, 255));
        lblVideo.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        lblVideo.setForeground(new java.awt.Color(255, 255, 255));
        lblVideo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblVideo.setText("Video & Movie");
        lblVideo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblVideo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVideoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblVideoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblVideoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout contVideoLayout = new javax.swing.GroupLayout(contVideo);
        contVideo.setLayout(contVideoLayout);
        contVideoLayout.setHorizontalGroup(
            contVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contVideoLayout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        contVideoLayout.setVerticalGroup(
            contVideoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contVideoLayout.createSequentialGroup()
                .addComponent(lblVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        contSound.setBackground(new java.awt.Color(244, 138, 0));
        contSound.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                contSoundMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                contSoundMouseExited(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Broadway", 1, 48)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText(">");

        lblSound.setBackground(new java.awt.Color(255, 255, 255));
        lblSound.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        lblSound.setForeground(new java.awt.Color(255, 255, 255));
        lblSound.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSound.setText("Sound & Music");
        lblSound.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSound.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSoundMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSoundMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSoundMouseExited(evt);
            }
        });

        javax.swing.GroupLayout contSoundLayout = new javax.swing.GroupLayout(contSound);
        contSound.setLayout(contSoundLayout);
        contSoundLayout.setHorizontalGroup(
            contSoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contSoundLayout.createSequentialGroup()
                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSound, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        contSoundLayout.setVerticalGroup(
            contSoundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contSoundLayout.createSequentialGroup()
                .addComponent(lblSound, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        contTemplate.setBackground(new java.awt.Color(244, 138, 0));
        contTemplate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                contTemplateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                contTemplateMouseExited(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Broadway", 1, 48)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText(">");

        lblTemplate.setBackground(new java.awt.Color(255, 255, 255));
        lblTemplate.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        lblTemplate.setForeground(new java.awt.Color(255, 255, 255));
        lblTemplate.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTemplate.setText("Template & Layout");
        lblTemplate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblTemplate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTemplateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblTemplateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblTemplateMouseExited(evt);
            }
        });

        javax.swing.GroupLayout contTemplateLayout = new javax.swing.GroupLayout(contTemplate);
        contTemplate.setLayout(contTemplateLayout);
        contTemplateLayout.setHorizontalGroup(
            contTemplateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contTemplateLayout.createSequentialGroup()
                .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTemplate, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        contTemplateLayout.setVerticalGroup(
            contTemplateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contTemplateLayout.createSequentialGroup()
                .addComponent(lblTemplate, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jPanel8.setBackground(new java.awt.Color(127, 0, 0));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/first.png"))); // NOI18N
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/prev.png"))); // NOI18N
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel25MouseClicked(evt);
            }
        });

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/play.png"))); // NOI18N

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/next.png"))); // NOI18N
        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel27MouseClicked(evt);
            }
        });

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/last.png"))); // NOI18N

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/stop.png"))); // NOI18N

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/fullscreen.png"))); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel18)
                .addGap(0, 0, 0)
                .addComponent(jLabel25)
                .addGap(0, 0, 0)
                .addComponent(jLabel26)
                .addGap(0, 0, 0)
                .addComponent(jLabel27)
                .addGap(0, 0, 0)
                .addComponent(jLabel28))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29)
                .addGap(135, 135, 135))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel30))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(jLabel18)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel29)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30))
        );

        javax.swing.GroupLayout mediaPanelLayout = new javax.swing.GroupLayout(mediaPanel);
        mediaPanel.setLayout(mediaPanelLayout);
        mediaPanelLayout.setHorizontalGroup(
            mediaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mediaPanelLayout.createSequentialGroup()
                .addGroup(mediaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(mediaPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(mediaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(contImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(contAnimated, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(contVideo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(contSound, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(contTemplate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(contTextBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(mediaPanelLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        mediaPanelLayout.setVerticalGroup(
            mediaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mediaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mediaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(contTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contAnimated, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contVideo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contSound, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contTemplate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );

        pbtnPreviewProject.setBackground(new java.awt.Color(127, 0, 0));

        lblProject6.setBackground(new java.awt.Color(255, 255, 255));
        lblProject6.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        lblProject6.setForeground(new java.awt.Color(240, 240, 240));
        lblProject6.setText("Preview");
        lblProject6.setAlignmentX(0.5F);
        lblProject6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblProject6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblProject6MouseClicked(evt);
            }
        });

        lblCloseProject6.setBackground(new java.awt.Color(229, 235, 240));
        lblCloseProject6.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        lblCloseProject6.setForeground(new java.awt.Color(255, 255, 255));
        lblCloseProject6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCloseProject6.setAlignmentX(0.5F);
        lblCloseProject6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCloseProject6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblCloseProject6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseProject6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pbtnPreviewProjectLayout = new javax.swing.GroupLayout(pbtnPreviewProject);
        pbtnPreviewProject.setLayout(pbtnPreviewProjectLayout);
        pbtnPreviewProjectLayout.setHorizontalGroup(
            pbtnPreviewProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pbtnPreviewProjectLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCloseProject6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblProject6, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))
        );
        pbtnPreviewProjectLayout.setVerticalGroup(
            pbtnPreviewProjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblProject6, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
            .addComponent(lblCloseProject6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlUtamaLayout = new javax.swing.GroupLayout(pnlUtama);
        pnlUtama.setLayout(pnlUtamaLayout);
        pnlUtamaLayout.setHorizontalGroup(
            pnlUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUtamaLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnlUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUtamaLayout.createSequentialGroup()
                        .addComponent(pnlProjectInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 715, Short.MAX_VALUE))
                    .addComponent(pnlProject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(pnlUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mediaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUtamaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pbtnPreviewProject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );
        pnlUtamaLayout.setVerticalGroup(
            pnlUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUtamaLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(pnlUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlProjectInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pbtnPreviewProject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(pnlUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mediaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlProject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11))
        );

        jMenuBar1.setName("Koobits"); // NOI18N
        jMenuBar1.setOpaque(false);

        jMenu1.setText("Library       ");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Local Library");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Online Library");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("File             ");

        jMenuItem3.setText("New");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("New From Template");
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Open");
        jMenu2.add(jMenuItem5);
        jMenu2.add(jSeparator1);

        jMenuItem6.setText("Reset");
        jMenu2.add(jMenuItem6);

        jMenuItem7.setText("Close");
        jMenu2.add(jMenuItem7);
        jMenu2.add(jSeparator2);

        jMenuItem8.setText("Save");
        jMenu2.add(jMenuItem8);

        jMenuItem9.setText("Save As");
        jMenu2.add(jMenuItem9);
        jMenu2.add(jSeparator3);

        jMenuItem10.setText("Publish");
        jMenu2.add(jMenuItem10);

        jMenuItem11.setText("Publish to Library");
        jMenu2.add(jMenuItem11);
        jMenu2.add(jSeparator4);

        jMenuItem12.setText("Print");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem12);

        jMenuItem13.setText("Export to Video");
        jMenu2.add(jMenuItem13);
        jMenu2.add(jSeparator5);

        jMenuItem14.setText("Exit");
        jMenu2.add(jMenuItem14);

        jMenuBar1.add(jMenu2);

        jMenu6.setText("Edit           ");

        jMenuItem15.setText("Undo");
        jMenu6.add(jMenuItem15);

        jMenuItem16.setText("Redo");
        jMenu6.add(jMenuItem16);
        jMenu6.add(jSeparator6);

        jMenuItem17.setText("Cut");
        jMenu6.add(jMenuItem17);

        jMenuItem18.setText("Copy");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem18);

        jMenuItem19.setText("Paste");
        jMenu6.add(jMenuItem19);

        jMenuItem20.setText("Delete");
        jMenu6.add(jMenuItem20);
        jMenu6.add(jSeparator7);

        jMenuItem26.setText("Duplicate");
        jMenu6.add(jMenuItem26);
        jMenu6.add(jSeparator8);

        jMenuItem21.setText("Password");
        jMenu6.add(jMenuItem21);

        jMenuItem22.setText("Book Summary");
        jMenu6.add(jMenuItem22);
        jMenu6.add(jSeparator9);

        jMenuItem23.setText("Page Background");
        jMenu6.add(jMenuItem23);

        jMenu5.setText("Exclusive Background");

        jMenuItem31.setText("Left Page");
        jMenu5.add(jMenuItem31);

        jMenuItem32.setText("Right Page");
        jMenu5.add(jMenuItem32);

        jMenu6.add(jMenu5);
        jMenu6.add(jSeparator10);

        jMenu7.setText("Transform");

        jMenuItem33.setText("Rotate 180");
        jMenu7.add(jMenuItem33);

        jMenuItem34.setText("Rotate 90 CW");
        jMenu7.add(jMenuItem34);

        jMenuItem35.setText("Rotate 90 CCW");
        jMenu7.add(jMenuItem35);

        jMenuItem36.setText("Flip Horizontal");
        jMenu7.add(jMenuItem36);

        jMenuItem37.setText("Flip Vertical");
        jMenu7.add(jMenuItem37);

        jMenu6.add(jMenu7);

        jMenuBar1.add(jMenu6);

        jMenu4.setText("View             ");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("Show Layer Panel");
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jCheckBoxMenuItem1);

        showEditPanel.setSelected(true);
        showEditPanel.setText("Show Edit Panel");
        showEditPanel.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                showEditPanelStateChanged(evt);
            }
        });
        showEditPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showEditPanelActionPerformed(evt);
            }
        });
        jMenu4.add(showEditPanel);

        showMediaPanel.setSelected(true);
        showMediaPanel.setText("Show Media Panel");
        showMediaPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showMediaPanelActionPerformed(evt);
            }
        });
        jMenu4.add(showMediaPanel);
        jMenu4.add(jSeparator11);

        jMenuItem30.setText("Read Mode");
        jMenu4.add(jMenuItem30);

        jMenuBar1.add(jMenu4);

        jMenu9.setText("Insert           ");

        jMenuItem38.setText("New Page");
        jMenu9.add(jMenuItem38);
        jMenu9.add(jSeparator12);

        jCheckBoxMenuItem4.setSelected(true);
        jCheckBoxMenuItem4.setText("Page Number");
        jMenu9.add(jCheckBoxMenuItem4);
        jMenu9.add(jSeparator13);

        jMenuItem39.setText("Text Input");
        jMenu9.add(jMenuItem39);

        jMenuItem40.setText("Auto text");
        jMenu9.add(jMenuItem40);

        jMenu10.setText("Picture");

        jMenuItem41.setText("Left Page");
        jMenu10.add(jMenuItem41);

        jMenuItem42.setText("Right Page");
        jMenu10.add(jMenuItem42);

        jMenu9.add(jMenu10);

        jMenu11.setText("Movie and Video");

        jMenuItem43.setText("Rotate 180");
        jMenu11.add(jMenuItem43);

        jMenuItem44.setText("Rotate 90 CW");
        jMenu11.add(jMenuItem44);

        jMenuItem45.setText("Rotate 90 CCW");
        jMenu11.add(jMenuItem45);

        jMenuItem46.setText("Flip Horizontal");
        jMenu11.add(jMenuItem46);

        jMenuItem47.setText("Flip Vertical");
        jMenu11.add(jMenuItem47);

        jMenu9.add(jMenu11);

        jMenu12.setText("Sound and Music");

        jMenuItem48.setText("Left Page");
        jMenu12.add(jMenuItem48);

        jMenuItem49.setText("Right Page");
        jMenu12.add(jMenuItem49);

        jMenu9.add(jMenu12);

        jMenu13.setText("3D Content");

        jMenuItem50.setText("Rotate 180");
        jMenu13.add(jMenuItem50);

        jMenuItem51.setText("Rotate 90 CW");
        jMenu13.add(jMenuItem51);

        jMenuItem52.setText("Rotate 90 CCW");
        jMenu13.add(jMenuItem52);

        jMenuItem53.setText("Flip Horizontal");
        jMenu13.add(jMenuItem53);

        jMenuItem54.setText("Flip Vertical");
        jMenu13.add(jMenuItem54);

        jMenu9.add(jMenu13);

        jMenuItem55.setText("KooBits Tune");
        jMenu9.add(jMenuItem55);

        jMenu14.setText("Transform");

        jMenuItem56.setText("Rotate 180");
        jMenu14.add(jMenuItem56);

        jMenuItem57.setText("Rotate 90 CW");
        jMenu14.add(jMenuItem57);

        jMenuItem58.setText("Rotate 90 CCW");
        jMenu14.add(jMenuItem58);

        jMenuItem59.setText("Flip Horizontal");
        jMenu14.add(jMenuItem59);

        jMenuItem60.setText("Flip Vertical");
        jMenu14.add(jMenuItem60);

        jMenu9.add(jMenu14);

        jMenuBar1.add(jMenu9);

        jMenu8.setText("Tools           ");

        jMenuItem64.setText("Spelling");
        jMenu8.add(jMenuItem64);

        jMenuItem65.setText("Options");
        jMenu8.add(jMenuItem65);

        jMenuBar1.add(jMenu8);

        jMenu3.setText("Help           ");

        jMenuItem24.setText("iSmart Help");
        jMenuItem24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem24ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem24);

        jMenuItem25.setText("Take a Quick Tour");
        jMenu3.add(jMenuItem25);

        jMenuItem27.setText("Show Start Page");
        jMenu3.add(jMenuItem27);
        jMenu3.add(jSeparator14);

        jMenuItem28.setText("iSmart Support Centre");
        jMenu3.add(jMenuItem28);

        jMenuItem29.setText("iSmart Community");
        jMenu3.add(jMenuItem29);

        jMenuItem61.setText("Online Registration");
        jMenuItem61.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem61ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem61);

        jMenuItem62.setText("Activate it");
        jMenu3.add(jMenuItem62);
        jMenu3.add(jSeparator15);

        jMenuItem63.setText("About iSmart");
        jMenuItem63.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem63ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem63);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlUtama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem61ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem61ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem61ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       localLibrary.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed

    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        new Library().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        closeBook();
        BookInfo bi = new BookInfo();
        bi.setVisible(true);       
        rightPage.setVisible(true);
        pnlProject.setVisible(true);
        pnlProjectInfo.setVisible(true);
        lblProject.setVisible(true);
        lblProject.setText("MyBook1");
        bersihkanCanvas();
        showPalette();
        leftPage.setVisible(false);
        leftPageNumber.setVisible(true);
        rightPageNumber.setVisible(true);
        leftPageNumber.setText("");
        rightPageNumber.setText("Cover");
        a = 1;
        leftPagePanel.setVisible(true);
        rightPagePanel.setVisible(true);
        pbtnPreviewProject.setVisible(true);
        //btnCloseBook.setEnabled(false);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
        editPanel.setVisible(true);
    }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

    private void showEditPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showEditPanelActionPerformed
         if (showEditPanel.isSelected() == true){
            editPanel.setVisible(true);
         }
         else{
            editPanel.setVisible(false);
         }
    }//GEN-LAST:event_showEditPanelActionPerformed

    private void showMediaPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showMediaPanelActionPerformed
         if (showMediaPanel.isSelected() == true){
            mediaPanel.setVisible(true);
         }
         else{
            mediaPanel.setVisible(false);
         }
    }//GEN-LAST:event_showMediaPanelActionPerformed

    private void showEditPanelStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_showEditPanelStateChanged
        
    }//GEN-LAST:event_showEditPanelStateChanged

    private void lblCloseProjectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseProjectMouseClicked
      
        pnlProject.setVisible(false);
        mediaPanel.setVisible(false);
        closeBook();
        
    }//GEN-LAST:event_lblCloseProjectMouseClicked

    private void lblImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImageMouseClicked
        Edit ed = new Edit();
        ed.setVisible(true);
        ed.rb2D.setSelected(true);
        ed.lblThumbnail.setText("2D Animation Files");
    }//GEN-LAST:event_lblImageMouseClicked

    private void lblAnimatedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAnimatedMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblAnimatedMouseClicked

    private void lblVideoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVideoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblVideoMouseClicked

    private void lblSoundMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSoundMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblSoundMouseClicked

    private void lblTemplateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTemplateMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTemplateMouseClicked

    private void contTextBoxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contTextBoxMouseEntered
        contTextBox.setBackground(Color.ORANGE);
    }//GEN-LAST:event_contTextBoxMouseEntered

    private void contTextBoxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contTextBoxMouseExited
        contTextBox.setBackground(mediaPanel.getBackground());
    }//GEN-LAST:event_contTextBoxMouseExited

    private void lblCloseProject6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseProject6MouseClicked
        
        
    }//GEN-LAST:event_lblCloseProject6MouseClicked

    private void lblProject6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProject6MouseClicked
        mediaPanel.setBackground(pbtnPreviewProject.getBackground());
        pnlProject.setBackground(pbtnPreviewProject.getBackground());
    }//GEN-LAST:event_lblProject6MouseClicked

    private void lblProjectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProjectMouseClicked
        mediaPanel.setBackground(pnlProjectInfo.getBackground());
        pnlProject.setBackground(pnlProjectInfo.getBackground());
    }//GEN-LAST:event_lblProjectMouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        rightPageNumber.setText("Cover");
        leftPageNumber.setText("");
        leftPage.setVisible(false);
        a = 1;
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseClicked
        if (a>3){
            leftPageNumber.setText("Page "+(a-4));
            rightPageNumber.setText("Page "+(a-3));
            a = a-2;            
        }
        else{
            rightPageNumber.setText("Cover");
            //jPanel4.revalidate();
            leftPageNumber.setText("");
            //leftPagePanel.setVisible(false);
            leftPage.setVisible(false);
            a = 1;
        }
    }//GEN-LAST:event_jLabel25MouseClicked

    private void jLabel27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseClicked
        leftPage.setVisible(true);
        int p = 6;
        if (a<=p){
            leftPagePanel.setVisible(true);
            rightPagePanel.setVisible(true);
            leftPageNumber.setText("Page "+a);
            rightPageNumber.setText("Page "+(a+1));
            a = a+2;            
        }
        else{
            JOptionPane.showMessageDialog(this,"Max Page");
            
        }
    }//GEN-LAST:event_jLabel27MouseClicked

    private void contImageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contImageMouseEntered
        contImage.setBackground(Color.ORANGE);        
    }//GEN-LAST:event_contImageMouseEntered

    private void contAnimatedMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contAnimatedMouseEntered
        contAnimated.setBackground(Color.ORANGE);
    }//GEN-LAST:event_contAnimatedMouseEntered

    private void contVideoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contVideoMouseEntered
        contVideo.setBackground(Color.ORANGE);
    }//GEN-LAST:event_contVideoMouseEntered

    private void contSoundMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contSoundMouseEntered
        contSound.setBackground(Color.ORANGE);
    }//GEN-LAST:event_contSoundMouseEntered

    private void contTemplateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contTemplateMouseEntered
        contTemplate.setBackground(Color.ORANGE);
    }//GEN-LAST:event_contTemplateMouseEntered

    private void contTemplateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contTemplateMouseExited
        contTemplate.setBackground(mediaPanel.getBackground());
    }//GEN-LAST:event_contTemplateMouseExited

    private void contImageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contImageMouseExited
        contImage.setBackground(mediaPanel.getBackground());
    }//GEN-LAST:event_contImageMouseExited

    private void contAnimatedMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contAnimatedMouseExited
        contAnimated.setBackground(mediaPanel.getBackground());
    }//GEN-LAST:event_contAnimatedMouseExited

    private void contVideoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contVideoMouseExited
        contVideo.setBackground(mediaPanel.getBackground());
    }//GEN-LAST:event_contVideoMouseExited

    private void contSoundMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contSoundMouseExited
        contSound.setBackground(mediaPanel.getBackground());
    }//GEN-LAST:event_contSoundMouseExited

    private void lblTextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTextMouseEntered
        contTextBox.setBackground(Color.ORANGE);                                          
    }//GEN-LAST:event_lblTextMouseEntered

    private void lblTextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTextMouseExited
        contTextBox.setBackground(mediaPanel.getBackground());
    }//GEN-LAST:event_lblTextMouseExited

    private void lblImageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImageMouseEntered
        contImage.setBackground(Color.ORANGE);
    }//GEN-LAST:event_lblImageMouseEntered

    private void lblImageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImageMouseExited
        contImage.setBackground(mediaPanel.getBackground());
    }//GEN-LAST:event_lblImageMouseExited

    private void lblAnimatedMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAnimatedMouseEntered
        contAnimated.setBackground(Color.ORANGE);
    }//GEN-LAST:event_lblAnimatedMouseEntered

    private void lblAnimatedMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAnimatedMouseExited
        contAnimated.setBackground(mediaPanel.getBackground());
    }//GEN-LAST:event_lblAnimatedMouseExited

    private void lblVideoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVideoMouseEntered
        contVideo.setBackground(Color.ORANGE);
    }//GEN-LAST:event_lblVideoMouseEntered

    private void lblVideoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVideoMouseExited
        contVideo.setBackground(mediaPanel.getBackground());
    }//GEN-LAST:event_lblVideoMouseExited

    private void lblSoundMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSoundMouseEntered
        contSound.setBackground(Color.ORANGE);
    }//GEN-LAST:event_lblSoundMouseEntered

    private void lblSoundMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSoundMouseExited
        contSound.setBackground(mediaPanel.getBackground());
    }//GEN-LAST:event_lblSoundMouseExited

    private void lblTemplateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTemplateMouseEntered
        contTemplate.setBackground(Color.ORANGE);
    }//GEN-LAST:event_lblTemplateMouseEntered

    private void lblTemplateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTemplateMouseExited
        contTemplate.setBackground(mediaPanel.getBackground());
    }//GEN-LAST:event_lblTemplateMouseExited

    private void jMenuItem24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem24ActionPerformed

    private void jMenuItem63ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem63ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem63ActionPerformed


    public static void main(String[] act) {
        try {
            UIManager.setLookAndFeel(new NimbusLookAndFeel());
            //UIManager.setLookAndFeel("joxy.JoxyLookAndFeel");

        } catch (Exception e) {
            e.printStackTrace();
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
                new WelcomePopup().setVisible(true);
            }
        });
    }
    
    
    public static BufferedImage loadImage(String ref) {
        BufferedImage bimg = null;
        try {
        bimg = ImageIO.read(new File(ref));
        } catch (Exception e) {
        e.printStackTrace();
        }
        return bimg;
    } 
    
    public static BufferedImage resize(BufferedImage img, int newW, int newH) {
        int w = img.getWidth();
        int h = img.getHeight();
        BufferedImage dimg = dimg = new BufferedImage(newW, newH, img.getType());
        Graphics2D g = dimg.createGraphics();
        g.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
        g.drawImage(img, 0, 0, newW, newH, 0, 0, w, h, null);
        g.dispose();
        return dimg;
    }
    
    public void closeBook(){
        pnlProjectInfo.setVisible(false);
        leftPagePanel.setVisible(false);
        rightPagePanel.setVisible(false);
        leftPageNumber.setVisible(false);
        rightPageNumber.setVisible(false);
        pbtnPreviewProject.setVisible(false);
        muzic m = new muzic();
        if (musicOn == true){
            m.close();
        }
    }
    
    
    public void tampilkanImage(){
            pack();
            
            String clipArtIcon = "src\\Image\\ClipArt.png";
            BufferedImage loadImg = loadImage(clipArtIcon);
            String videoIcon = "src\\Image\\Text.png";
            BufferedImage loadImg2 = loadImage(videoIcon);
            //ImageIcon imageIcon = new ImageIcon(resize(loadImg, btnClipArt.getWidth(), btnClipArt.getHeight()));
            //btnClipArt.setIcon(imageIcon);
            //ImageIcon imageIcon2 = new ImageIcon(resize(loadImg2, btnVideo.getWidth(), btnVideo.getHeight()));
            //btnVideo.setIcon(imageIcon2);
    } 
    
    public void bersihkanCanvas(){
            //pack();
            rightPage.setIcon(null);
    } 
    
    public void showPalette(){
        editPanel.setVisible(true);
        mediaPanel.setVisible(true);            
    } 
    



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn1;
    private javax.swing.JPanel contAnimated;
    private javax.swing.JPanel contImage;
    private javax.swing.JPanel contSound;
    private javax.swing.JPanel contTemplate;
    private javax.swing.JPanel contTextBox;
    private javax.swing.JPanel contVideo;
    private javax.swing.JPanel editPanel;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem29;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem30;
    private javax.swing.JMenuItem jMenuItem31;
    private javax.swing.JMenuItem jMenuItem32;
    private javax.swing.JMenuItem jMenuItem33;
    private javax.swing.JMenuItem jMenuItem34;
    private javax.swing.JMenuItem jMenuItem35;
    private javax.swing.JMenuItem jMenuItem36;
    private javax.swing.JMenuItem jMenuItem37;
    private javax.swing.JMenuItem jMenuItem38;
    private javax.swing.JMenuItem jMenuItem39;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem40;
    private javax.swing.JMenuItem jMenuItem41;
    private javax.swing.JMenuItem jMenuItem42;
    private javax.swing.JMenuItem jMenuItem43;
    private javax.swing.JMenuItem jMenuItem44;
    private javax.swing.JMenuItem jMenuItem45;
    private javax.swing.JMenuItem jMenuItem46;
    private javax.swing.JMenuItem jMenuItem47;
    private javax.swing.JMenuItem jMenuItem48;
    private javax.swing.JMenuItem jMenuItem49;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem50;
    private javax.swing.JMenuItem jMenuItem51;
    private javax.swing.JMenuItem jMenuItem52;
    private javax.swing.JMenuItem jMenuItem53;
    private javax.swing.JMenuItem jMenuItem54;
    private javax.swing.JMenuItem jMenuItem55;
    private javax.swing.JMenuItem jMenuItem56;
    private javax.swing.JMenuItem jMenuItem57;
    private javax.swing.JMenuItem jMenuItem58;
    private javax.swing.JMenuItem jMenuItem59;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem60;
    private javax.swing.JMenuItem jMenuItem61;
    private javax.swing.JMenuItem jMenuItem62;
    private javax.swing.JMenuItem jMenuItem63;
    private javax.swing.JMenuItem jMenuItem64;
    private javax.swing.JMenuItem jMenuItem65;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator11;
    private javax.swing.JPopupMenu.Separator jSeparator12;
    private javax.swing.JPopupMenu.Separator jSeparator13;
    private javax.swing.JPopupMenu.Separator jSeparator14;
    private javax.swing.JPopupMenu.Separator jSeparator15;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JLabel lblAnimated;
    private javax.swing.JLabel lblCloseProject;
    private javax.swing.JLabel lblCloseProject6;
    private javax.swing.JLabel lblImage;
    public static javax.swing.JLabel lblProject;
    public static javax.swing.JLabel lblProject6;
    private javax.swing.JLabel lblSound;
    private javax.swing.JLabel lblTemplate;
    private javax.swing.JLabel lblText;
    private javax.swing.JLabel lblVideo;
    private javax.swing.JLabel leftPage;
    private javax.swing.JLabel leftPageNumber;
    private javax.swing.JPanel leftPagePanel;
    private javax.swing.JPanel mediaPanel;
    private javax.swing.JPanel pbtnPreviewProject;
    private javax.swing.JPanel pnlProject;
    private javax.swing.JPanel pnlProjectInfo;
    public javax.swing.JPanel pnlUtama;
    private javax.swing.JLabel rightPage;
    private javax.swing.JLabel rightPageNumber;
    private javax.swing.JPanel rightPagePanel;
    private javax.swing.JCheckBoxMenuItem showEditPanel;
    private javax.swing.JCheckBoxMenuItem showMediaPanel;
    // End of variables declaration//GEN-END:variables
 

}
